// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "time"

type HardwareProfile struct {
	// Arch corresponds to the JSON schema field "arch".
	Arch string `json:"arch" yaml:"arch" mapstructure:"arch"`

	// CpuCoresLogical corresponds to the JSON schema field "cpu_cores_logical".
	CpuCoresLogical *int `json:"cpu_cores_logical,omitempty" yaml:"cpu_cores_logical,omitempty" mapstructure:"cpu_cores_logical,omitempty"`

	// CpuCoresPhysical corresponds to the JSON schema field "cpu_cores_physical".
	CpuCoresPhysical *int `json:"cpu_cores_physical,omitempty" yaml:"cpu_cores_physical,omitempty" mapstructure:"cpu_cores_physical,omitempty"`

	// CpuModel corresponds to the JSON schema field "cpu_model".
	CpuModel *string `json:"cpu_model,omitempty" yaml:"cpu_model,omitempty" mapstructure:"cpu_model,omitempty"`

	// Gpus corresponds to the JSON schema field "gpus".
	Gpus []HardwareProfileGpusElem `json:"gpus,omitempty" yaml:"gpus,omitempty" mapstructure:"gpus,omitempty"`

	// Hash of the canonical hardware fields, so identical rigs cluster
	Id *string `json:"id,omitempty" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Os corresponds to the JSON schema field "os".
	Os string `json:"os" yaml:"os" mapstructure:"os"`

	// OsVersion corresponds to the JSON schema field "os_version".
	OsVersion *string `json:"os_version,omitempty" yaml:"os_version,omitempty" mapstructure:"os_version,omitempty"`

	// RamGb corresponds to the JSON schema field "ram_gb".
	RamGb *float64 `json:"ram_gb,omitempty" yaml:"ram_gb,omitempty" mapstructure:"ram_gb,omitempty"`

	// UnifiedMemory corresponds to the JSON schema field "unified_memory".
	UnifiedMemory *bool `json:"unified_memory,omitempty" yaml:"unified_memory,omitempty" mapstructure:"unified_memory,omitempty"`
}

type HardwareProfileGpusElem struct {
	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Vendor corresponds to the JSON schema field "vendor".
	Vendor *string `json:"vendor,omitempty" yaml:"vendor,omitempty" mapstructure:"vendor,omitempty"`

	// VramGb corresponds to the JSON schema field "vram_gb".
	VramGb *float64 `json:"vram_gb,omitempty" yaml:"vram_gb,omitempty" mapstructure:"vram_gb,omitempty"`
}

// A single aiMark benchmark run: one suite executed against one target with one
// parameter vector. This envelope is what `aimark submit` sends (raw samples
// upload separately to blob storage).
type RunV1Json struct {
	// Cli corresponds to the JSON schema field "cli".
	Cli RunV1JsonCli `json:"cli" yaml:"cli" mapstructure:"cli"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Environment corresponds to the JSON schema field "environment".
	Environment *RunV1JsonEnvironment `json:"environment,omitempty" yaml:"environment,omitempty" mapstructure:"environment,omitempty"`

	// Integrity corresponds to the JSON schema field "integrity".
	Integrity *RunV1JsonIntegrity `json:"integrity,omitempty" yaml:"integrity,omitempty" mapstructure:"integrity,omitempty"`

	// Aggregate metrics keyed by metric id (ttft_ms_p50, decode_tps_mean, ...)
	Metrics RunV1JsonMetrics `json:"metrics" yaml:"metrics" mapstructure:"metrics"`

	// Hosted track: provider pricing at run time
	PricingSnapshot *RunV1JsonPricingSnapshot `json:"pricing_snapshot,omitempty" yaml:"pricing_snapshot,omitempty" mapstructure:"pricing_snapshot,omitempty"`

	// Scores the CLI computed locally; the server recompute is canonical
	ProvisionalScores *RunV1JsonProvisionalScores `json:"provisional_scores,omitempty" yaml:"provisional_scores,omitempty" mapstructure:"provisional_scores,omitempty"`

	// ULID assigned by the CLI at run start
	RunId string `json:"run_id" yaml:"run_id" mapstructure:"run_id"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// Where the run originated. The CLI auto-detects CI environments
	// (CI/GITHUB_ACTIONS env vars) and flags them; ci and dev runs are excluded from
	// default leaderboards.
	Source RunV1JsonSource `json:"source" yaml:"source" mapstructure:"source"`

	// Suite corresponds to the JSON schema field "suite".
	Suite RunV1JsonSuite `json:"suite" yaml:"suite" mapstructure:"suite"`

	// Shared ULID when this run is one cell of a parameter sweep
	SweepId *string `json:"sweep_id,omitempty" yaml:"sweep_id,omitempty" mapstructure:"sweep_id,omitempty"`

	// Target corresponds to the JSON schema field "target".
	Target RunV1JsonTarget `json:"target" yaml:"target" mapstructure:"target"`
}

type RunV1JsonCli struct {
	// Arch corresponds to the JSON schema field "arch".
	Arch RunV1JsonCliArch `json:"arch" yaml:"arch" mapstructure:"arch"`

	// Commit corresponds to the JSON schema field "commit".
	Commit *string `json:"commit,omitempty" yaml:"commit,omitempty" mapstructure:"commit,omitempty"`

	// Os corresponds to the JSON schema field "os".
	Os RunV1JsonCliOs `json:"os" yaml:"os" mapstructure:"os"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type RunV1JsonCliArch string

const RunV1JsonCliArchAmd64 RunV1JsonCliArch = "amd64"
const RunV1JsonCliArchArm64 RunV1JsonCliArch = "arm64"

type RunV1JsonCliOs string

const RunV1JsonCliOsDarwin RunV1JsonCliOs = "darwin"
const RunV1JsonCliOsLinux RunV1JsonCliOs = "linux"
const RunV1JsonCliOsWindows RunV1JsonCliOs = "windows"

type RunV1JsonEnvironment struct {
	// HardwareProfile corresponds to the JSON schema field "hardware_profile".
	HardwareProfile *HardwareProfile `json:"hardware_profile,omitempty" yaml:"hardware_profile,omitempty" mapstructure:"hardware_profile,omitempty"`

	// Pre-flight RTT to the hosted endpoint, reported separately from TTFT
	NetworkRttMs *float64 `json:"network_rtt_ms,omitempty" yaml:"network_rtt_ms,omitempty" mapstructure:"network_rtt_ms,omitempty"`
}

type RunV1JsonIntegrity struct {
	// Hmac corresponds to the JSON schema field "hmac".
	Hmac *string `json:"hmac,omitempty" yaml:"hmac,omitempty" mapstructure:"hmac,omitempty"`

	// CLI release key generation identifier
	KeyGen *string `json:"key_gen,omitempty" yaml:"key_gen,omitempty" mapstructure:"key_gen,omitempty"`

	// Nonce corresponds to the JSON schema field "nonce".
	Nonce string `json:"nonce" yaml:"nonce" mapstructure:"nonce"`

	// PayloadSha256 corresponds to the JSON schema field "payload_sha256".
	PayloadSha256 string `json:"payload_sha256" yaml:"payload_sha256" mapstructure:"payload_sha256"`
}

// Aggregate metrics keyed by metric id (ttft_ms_p50, decode_tps_mean, ...)
type RunV1JsonMetrics map[string]float64

// Hosted track: provider pricing at run time
type RunV1JsonPricingSnapshot struct {
	// CapturedAt corresponds to the JSON schema field "captured_at".
	CapturedAt *time.Time `json:"captured_at,omitempty" yaml:"captured_at,omitempty" mapstructure:"captured_at,omitempty"`

	// Currency corresponds to the JSON schema field "currency".
	Currency *string `json:"currency,omitempty" yaml:"currency,omitempty" mapstructure:"currency,omitempty"`

	// InputPerMtok corresponds to the JSON schema field "input_per_mtok".
	InputPerMtok *float64 `json:"input_per_mtok,omitempty" yaml:"input_per_mtok,omitempty" mapstructure:"input_per_mtok,omitempty"`

	// OutputPerMtok corresponds to the JSON schema field "output_per_mtok".
	OutputPerMtok *float64 `json:"output_per_mtok,omitempty" yaml:"output_per_mtok,omitempty" mapstructure:"output_per_mtok,omitempty"`
}

// Scores the CLI computed locally; the server recompute is canonical
type RunV1JsonProvisionalScores struct {
	// Composite corresponds to the JSON schema field "composite".
	Composite *float64 `json:"composite,omitempty" yaml:"composite,omitempty" mapstructure:"composite,omitempty"`

	// Consistency corresponds to the JSON schema field "consistency".
	Consistency *float64 `json:"consistency,omitempty" yaml:"consistency,omitempty" mapstructure:"consistency,omitempty"`

	// CostEfficiency corresponds to the JSON schema field "cost_efficiency".
	CostEfficiency *float64 `json:"cost_efficiency,omitempty" yaml:"cost_efficiency,omitempty" mapstructure:"cost_efficiency,omitempty"`

	// Performance corresponds to the JSON schema field "performance".
	Performance *float64 `json:"performance,omitempty" yaml:"performance,omitempty" mapstructure:"performance,omitempty"`

	// Quality corresponds to the JSON schema field "quality".
	Quality *float64 `json:"quality,omitempty" yaml:"quality,omitempty" mapstructure:"quality,omitempty"`
}

type RunV1JsonSource string

const RunV1JsonSourceCi RunV1JsonSource = "ci"
const RunV1JsonSourceDev RunV1JsonSource = "dev"
const RunV1JsonSourceUser RunV1JsonSource = "user"

type RunV1JsonSuite struct {
	// Suite family, e.g. "sprint"
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// SHA-256 of the frozen suite manifest the CLI executed
	ProtocolHash *string `json:"protocol_hash,omitempty" yaml:"protocol_hash,omitempty" mapstructure:"protocol_hash,omitempty"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

type RunV1JsonTarget struct {
	// Declared parameter count in billions, when known
	DeclaredParamsB *float64 `json:"declared_params_b,omitempty" yaml:"declared_params_b,omitempty" mapstructure:"declared_params_b,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind RunV1JsonTargetKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Model identifier as the target reports it
	Model string `json:"model" yaml:"model" mapstructure:"model"`

	// Content digest of the model weights where the runtime exposes one
	ModelDigest *string `json:"model_digest,omitempty" yaml:"model_digest,omitempty" mapstructure:"model_digest,omitempty"`

	// Captured request parameter vector (num_ctx, concurrency, temperature,
	// prompt_caching, ...)
	Params RunV1JsonTargetParams `json:"params,omitempty" yaml:"params,omitempty" mapstructure:"params,omitempty"`

	// Hosted provider id (anthropic, openai, google, bedrock, openrouter) — hosted
	// kind only
	Provider *string `json:"provider,omitempty" yaml:"provider,omitempty" mapstructure:"provider,omitempty"`

	// Quantization corresponds to the JSON schema field "quantization".
	Quantization *string `json:"quantization,omitempty" yaml:"quantization,omitempty" mapstructure:"quantization,omitempty"`

	// Region corresponds to the JSON schema field "region".
	Region *string `json:"region,omitempty" yaml:"region,omitempty" mapstructure:"region,omitempty"`

	// Local runtime id (ollama, llamacpp, vllm, lmstudio) — local kind only
	Runtime *string `json:"runtime,omitempty" yaml:"runtime,omitempty" mapstructure:"runtime,omitempty"`

	// RuntimeVersion corresponds to the JSON schema field "runtime_version".
	RuntimeVersion *string `json:"runtime_version,omitempty" yaml:"runtime_version,omitempty" mapstructure:"runtime_version,omitempty"`
}

type RunV1JsonTargetKind string

const RunV1JsonTargetKindHosted RunV1JsonTargetKind = "hosted"
const RunV1JsonTargetKindLocal RunV1JsonTargetKind = "local"

// Captured request parameter vector (num_ctx, concurrency, temperature,
// prompt_caching, ...)
type RunV1JsonTargetParams map[string]interface{}

// Raw per-request samples for one run. Stored alongside the run envelope locally
// and uploaded to blob storage (R2) on submit — never to the relational DB.
type SamplesV1Json struct {
	// RunId corresponds to the JSON schema field "run_id".
	RunId string `json:"run_id" yaml:"run_id" mapstructure:"run_id"`

	// Samples corresponds to the JSON schema field "samples".
	Samples []SamplesV1JsonSamplesElem `json:"samples" yaml:"samples" mapstructure:"samples"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion string `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`
}

type SamplesV1JsonSamplesElem struct {
	// Concurrency corresponds to the JSON schema field "concurrency".
	Concurrency *int `json:"concurrency,omitempty" yaml:"concurrency,omitempty" mapstructure:"concurrency,omitempty"`

	// DecodeTps corresponds to the JSON schema field "decode_tps".
	DecodeTps *float64 `json:"decode_tps,omitempty" yaml:"decode_tps,omitempty" mapstructure:"decode_tps,omitempty"`

	// Error corresponds to the JSON schema field "error".
	Error *string `json:"error,omitempty" yaml:"error,omitempty" mapstructure:"error,omitempty"`

	// Quality suites: objective grading outcome
	Grade *SamplesV1JsonSamplesElemGrade `json:"grade,omitempty" yaml:"grade,omitempty" mapstructure:"grade,omitempty"`

	// InputTokens corresponds to the JSON schema field "input_tokens".
	InputTokens *int `json:"input_tokens,omitempty" yaml:"input_tokens,omitempty" mapstructure:"input_tokens,omitempty"`

	// InterTokenMsMean corresponds to the JSON schema field "inter_token_ms_mean".
	InterTokenMsMean *float64 `json:"inter_token_ms_mean,omitempty" yaml:"inter_token_ms_mean,omitempty" mapstructure:"inter_token_ms_mean,omitempty"`

	// LatencyMs corresponds to the JSON schema field "latency_ms".
	LatencyMs *float64 `json:"latency_ms,omitempty" yaml:"latency_ms,omitempty" mapstructure:"latency_ms,omitempty"`

	// OutputTokens corresponds to the JSON schema field "output_tokens".
	OutputTokens *int `json:"output_tokens,omitempty" yaml:"output_tokens,omitempty" mapstructure:"output_tokens,omitempty"`

	// Repetition corresponds to the JSON schema field "repetition".
	Repetition int `json:"repetition" yaml:"repetition" mapstructure:"repetition"`

	// StartedAt corresponds to the JSON schema field "started_at".
	StartedAt time.Time `json:"started_at" yaml:"started_at" mapstructure:"started_at"`

	// Status corresponds to the JSON schema field "status".
	Status SamplesV1JsonSamplesElemStatus `json:"status" yaml:"status" mapstructure:"status"`

	// TaskId corresponds to the JSON schema field "task_id".
	TaskId string `json:"task_id" yaml:"task_id" mapstructure:"task_id"`

	// First content token, stream-event level, monotonic clock
	TtftMs *float64 `json:"ttft_ms,omitempty" yaml:"ttft_ms,omitempty" mapstructure:"ttft_ms,omitempty"`

	// Warmup samples are recorded but excluded from metrics
	Warmup *bool `json:"warmup,omitempty" yaml:"warmup,omitempty" mapstructure:"warmup,omitempty"`
}

// Quality suites: objective grading outcome
type SamplesV1JsonSamplesElemGrade struct {
	// Detail corresponds to the JSON schema field "detail".
	Detail *string `json:"detail,omitempty" yaml:"detail,omitempty" mapstructure:"detail,omitempty"`

	// Passed corresponds to the JSON schema field "passed".
	Passed *bool `json:"passed,omitempty" yaml:"passed,omitempty" mapstructure:"passed,omitempty"`
}

type SamplesV1JsonSamplesElemStatus string

const SamplesV1JsonSamplesElemStatusError SamplesV1JsonSamplesElemStatus = "error"
const SamplesV1JsonSamplesElemStatusOk SamplesV1JsonSamplesElemStatus = "ok"
const SamplesV1JsonSamplesElemStatusTimeout SamplesV1JsonSamplesElemStatus = "timeout"

type SubScoreSpec struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics []SubScoreSpecMetricsElem `json:"metrics" yaml:"metrics" mapstructure:"metrics"`
}

type SubScoreSpecMetricsElem struct {
	// Key corresponds to the JSON schema field "key".
	Key string `json:"key" yaml:"key" mapstructure:"key"`

	// LowerIsBetter corresponds to the JSON schema field "lower_is_better".
	LowerIsBetter *bool `json:"lower_is_better,omitempty" yaml:"lower_is_better,omitempty" mapstructure:"lower_is_better,omitempty"`

	// Reference corresponds to the JSON schema field "reference".
	Reference float64 `json:"reference" yaml:"reference" mapstructure:"reference"`

	// Weight corresponds to the JSON schema field "weight".
	Weight float64 `json:"weight" yaml:"weight" mapstructure:"weight"`
}

// A frozen benchmark suite definition. Weights, reference baselines, prompts, and
// protocol are data — bumping any of them requires a new suite version (new
// leaderboard).
type SuiteManifestV1Json struct {
	// Description corresponds to the JSON schema field "description".
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Hard physical bounds per metric; submissions outside are auto-flagged
	Plausibility SuiteManifestV1JsonPlausibility `json:"plausibility,omitempty" yaml:"plausibility,omitempty" mapstructure:"plausibility,omitempty"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol SuiteManifestV1JsonProtocol `json:"protocol" yaml:"protocol" mapstructure:"protocol"`

	// Provenance of the reference baseline that anchors this suite's 1000-point scale
	Reference *SuiteManifestV1JsonReference `json:"reference,omitempty" yaml:"reference,omitempty" mapstructure:"reference,omitempty"`

	// Scoring corresponds to the JSON schema field "scoring".
	Scoring SuiteManifestV1JsonScoring `json:"scoring" yaml:"scoring" mapstructure:"scoring"`

	// Only frozen suites produce comparable leaderboard scores
	Status SuiteManifestV1JsonStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Tasks corresponds to the JSON schema field "tasks".
	Tasks []SuiteManifestV1JsonTasksElem `json:"tasks" yaml:"tasks" mapstructure:"tasks"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// Tracks corresponds to the JSON schema field "tracks".
	Tracks []SuiteManifestV1JsonTracksElem `json:"tracks" yaml:"tracks" mapstructure:"tracks"`

	// Version corresponds to the JSON schema field "version".
	Version int `json:"version" yaml:"version" mapstructure:"version"`
}

// Hard physical bounds per metric; submissions outside are auto-flagged
type SuiteManifestV1JsonPlausibility map[string]struct {
	// Max corresponds to the JSON schema field "max".
	Max *float64 `json:"max,omitempty" yaml:"max,omitempty" mapstructure:"max,omitempty"`

	// Min corresponds to the JSON schema field "min".
	Min *float64 `json:"min,omitempty" yaml:"min,omitempty" mapstructure:"min,omitempty"`
}

type SuiteManifestV1JsonProtocol struct {
	// Marathon-style suites run the task set at each level
	ConcurrencyLevels []int `json:"concurrency_levels,omitempty" yaml:"concurrency_levels,omitempty" mapstructure:"concurrency_levels,omitempty"`

	// Decoding corresponds to the JSON schema field "decoding".
	Decoding SuiteManifestV1JsonProtocolDecoding `json:"decoding" yaml:"decoding" mapstructure:"decoding"`

	// Repetitions corresponds to the JSON schema field "repetitions".
	Repetitions int `json:"repetitions" yaml:"repetitions" mapstructure:"repetitions"`

	// RequestTimeoutMs corresponds to the JSON schema field "request_timeout_ms".
	RequestTimeoutMs int `json:"request_timeout_ms" yaml:"request_timeout_ms" mapstructure:"request_timeout_ms"`

	// Streaming corresponds to the JSON schema field "streaming".
	Streaming bool `json:"streaming" yaml:"streaming" mapstructure:"streaming"`

	// WarmupRequests corresponds to the JSON schema field "warmup_requests".
	WarmupRequests int `json:"warmup_requests" yaml:"warmup_requests" mapstructure:"warmup_requests"`
}

type SuiteManifestV1JsonProtocolDecoding struct {
	// MaxTokens corresponds to the JSON schema field "max_tokens".
	MaxTokens int `json:"max_tokens" yaml:"max_tokens" mapstructure:"max_tokens"`

	// Temperature corresponds to the JSON schema field "temperature".
	Temperature float64 `json:"temperature" yaml:"temperature" mapstructure:"temperature"`
}

// Provenance of the reference baseline that anchors this suite's 1000-point scale
type SuiteManifestV1JsonReference struct {
	// Label corresponds to the JSON schema field "label".
	Label *string `json:"label,omitempty" yaml:"label,omitempty" mapstructure:"label,omitempty"`

	// Notes corresponds to the JSON schema field "notes".
	Notes *string `json:"notes,omitempty" yaml:"notes,omitempty" mapstructure:"notes,omitempty"`
}

type SuiteManifestV1JsonScoring struct {
	// CompositeWeights corresponds to the JSON schema field "composite_weights".
	CompositeWeights SuiteManifestV1JsonScoringCompositeWeights `json:"composite_weights" yaml:"composite_weights" mapstructure:"composite_weights"`

	// Consistency corresponds to the JSON schema field "consistency".
	Consistency *SubScoreSpec `json:"consistency,omitempty" yaml:"consistency,omitempty" mapstructure:"consistency,omitempty"`

	// CostEfficiency corresponds to the JSON schema field "cost_efficiency".
	CostEfficiency *SubScoreSpec `json:"cost_efficiency,omitempty" yaml:"cost_efficiency,omitempty" mapstructure:"cost_efficiency,omitempty"`

	// Performance corresponds to the JSON schema field "performance".
	Performance *SubScoreSpec `json:"performance,omitempty" yaml:"performance,omitempty" mapstructure:"performance,omitempty"`

	// Quality corresponds to the JSON schema field "quality".
	Quality *SubScoreSpec `json:"quality,omitempty" yaml:"quality,omitempty" mapstructure:"quality,omitempty"`
}

type SuiteManifestV1JsonScoringCompositeWeights map[string]float64

type SuiteManifestV1JsonStatus string

const SuiteManifestV1JsonStatusDraft SuiteManifestV1JsonStatus = "draft"
const SuiteManifestV1JsonStatusFrozen SuiteManifestV1JsonStatus = "frozen"
const SuiteManifestV1JsonStatusRetired SuiteManifestV1JsonStatus = "retired"

type SuiteManifestV1JsonTasksElem struct {
	// Objective grading spec (quality suites). Absent for pure-latency suites.
	Grading *SuiteManifestV1JsonTasksElemGrading `json:"grading,omitempty" yaml:"grading,omitempty" mapstructure:"grading,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Prompt corresponds to the JSON schema field "prompt".
	Prompt string `json:"prompt" yaml:"prompt" mapstructure:"prompt"`

	// System corresponds to the JSON schema field "system".
	System *string `json:"system,omitempty" yaml:"system,omitempty" mapstructure:"system,omitempty"`
}

// Objective grading spec (quality suites). Absent for pure-latency suites.
type SuiteManifestV1JsonTasksElemGrading struct {
	// Expected corresponds to the JSON schema field "expected".
	Expected interface{} `json:"expected,omitempty" yaml:"expected,omitempty" mapstructure:"expected,omitempty"`

	// Kind corresponds to the JSON schema field "kind".
	Kind SuiteManifestV1JsonTasksElemGradingKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// RequiredSubstrings corresponds to the JSON schema field "required_substrings".
	RequiredSubstrings []string `json:"required_substrings,omitempty" yaml:"required_substrings,omitempty" mapstructure:"required_substrings,omitempty"`

	// Schema corresponds to the JSON schema field "schema".
	Schema SuiteManifestV1JsonTasksElemGradingSchema `json:"schema,omitempty" yaml:"schema,omitempty" mapstructure:"schema,omitempty"`

	// JS test source for goja (Forge)
	Tests *string `json:"tests,omitempty" yaml:"tests,omitempty" mapstructure:"tests,omitempty"`

	// Tolerance corresponds to the JSON schema field "tolerance".
	Tolerance *float64 `json:"tolerance,omitempty" yaml:"tolerance,omitempty" mapstructure:"tolerance,omitempty"`
}

type SuiteManifestV1JsonTasksElemGradingKind string

const SuiteManifestV1JsonTasksElemGradingKindContainsAll SuiteManifestV1JsonTasksElemGradingKind = "contains_all"
const SuiteManifestV1JsonTasksElemGradingKindExact SuiteManifestV1JsonTasksElemGradingKind = "exact"
const SuiteManifestV1JsonTasksElemGradingKindJsTests SuiteManifestV1JsonTasksElemGradingKind = "js_tests"
const SuiteManifestV1JsonTasksElemGradingKindJsonSchema SuiteManifestV1JsonTasksElemGradingKind = "json_schema"
const SuiteManifestV1JsonTasksElemGradingKindNumericTolerance SuiteManifestV1JsonTasksElemGradingKind = "numeric_tolerance"

type SuiteManifestV1JsonTasksElemGradingSchema map[string]interface{}

type SuiteManifestV1JsonTracksElem string

const SuiteManifestV1JsonTracksElemHosted SuiteManifestV1JsonTracksElem = "hosted"
const SuiteManifestV1JsonTracksElemLocal SuiteManifestV1JsonTracksElem = "local"
